pipeline {
    agent any
    stages {
        stage('Clear & Build') {
            steps {
                parallel(
                    clean: {
                        sh 'rm -r allure-results'
                    }
                    build: {
                        sh 'mvn install -DskipTests'
                    }
                )
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -Dgroups='${Tag}'"
            }
        }
    }
    post {
        always {
            allure([
                    includeProperties: false,
                    jdk: '',
                    properties: [],
                    reportBuildPolicy: 'ALWAYS',
                    results: [[path: 'allure-results']]
            ])
        }
    }
}